- name: Install the required packages
  ansible.builtin.apt: 
    name: "{{ item }}"
    update_cache: true
    state: latest
  loop: "{{ packages }}"
  vars:
    packages:
      - gnupg2
      - nginx-full
      - sudo
      - curl
      - apt-transport-https
      - fail2ban
